const langCodes = {
    ar: "Arabic",
    az: "Azerbaijani",
    ca: "Catalan",
    zh: "Chinese",
    cs: "Czech",
    da: "Danish",
    nl: "Dutch ",
    en: "English",
    eo: "Esperanto",
    et: "Estonian",
    fi: "Finnish",
    fr: "French",
    de: "German",
    el: "Greek",
    he: "Hebrew",
    hi: "Hindi",
    hu: "Hungarian",
    id: "Indonesian",
    ga: "Irish",
    it: "Italian",
    ja: "Japanese",
    ko: "Korean",
    fa: "Persian",
    pl: "Polish",
    pt: "Portuguese",
    ru: "Russian",
    sk: "Slovak",
    es: "Spanish",
    sv: "Swedish",
    tr: "Turkish",
    uk: "Ukrainian",
  };
  